### ISSUE TITLE
greasyfork上面有个抄袭

### ISSUE THREAD

**Issue by BrendanLiu** [zarkin404/sweater#11]
留了个QQ群，QQ群还需付费，建议开发者关注一下
https://greasyfork.org/zh-CN/scripts/404411-2020%E4%BA%AC%E4%B8%9C618%E5%8F%A0%E8%9B%8B%E7%B3%95

**Comment by ericellis7** [comment]
> 留了个QQ群，QQ群还需付费，建议开发者关注一下
> https://greasyfork.org/zh-CN/scripts/404411-2020%E4%BA%AC%E4%B8%9C618%E5%8F%A0%E8%9B%8B%E7%B3%95

+1 、这种人太可恨

**Comment by xoyi** [comment]
多去举报

**Comment by elevenwd** [comment]
代码还一模一样，举报之

**Comment by wenjunzhangp** [comment]
已经举报了，这种垃圾人真的恶心，人家的开源作品，拿去就收费哈哈哒

**Comment by 1016797313** [comment]
https://github.com/itas109 疑似是那人的github

**Comment by zarkin404** [comment]
谢谢大家，实在是太坏了，居然没有附上我仓库的信息 🙃🙃🙃

**Comment by h-ecstasy** [comment]
偷盗可耻

**Comment by BrendanLiu** [comment]
> 谢谢大家，实在是太坏了，居然没有附上我仓库的信息 🙃🙃🙃

原链接已被删除，现在又上线了个新链接，新链接中的代码也无作者的信息
https://greasyfork.org/zh-CN/scripts/404793-2020%E4%BA%AC%E4%B8%9C618%E5%8F%A0%E8%9B%8B%E7%B3%95
