### ISSUE TITLE
登录验证滑动解锁不可用

### ISSUE THREAD

**Issue by ericellis7** [zarkin404/sweater#12]
登录验证时候，出现滑动解锁验证，下面滑动条无法选中以及拖动。

**Comment by elevenwd** [comment]
这是京东网站的问题吧，建议找京东客服

**Comment by xoyi** [comment]
> 登录验证时候，出现滑动解锁验证，下面滑动条无法选中以及拖动。

先选择正常手机模式，选那个iphone6或者x啥的就可以了，选完登录完成在切换新增的jdapp

**Comment by ericellis7** [comment]
> > 登录验证时候，出现滑动解锁验证，下面滑动条无法选中以及拖动。
> 
> 先选择正常手机模式，选那个iphone6或者x啥的就可以了，选完登录完成在切换新增的jdapp

不明白

**Comment by zarkin404** [comment]
你按 Ctrl + Shift + M 切换到移动端模式应该就好了。
