### ISSUE TITLE
受到大佬启发, 分享一个京东萌宠的

### ISSUE THREAD

**Issue by liuxiaoyucc** [zarkin404/sweater#14]
之前一直扔在服务端自用, 看到这个项目, 用我这拙劣的JS也写了一下
https://github.com/liuxiaoyucc/jd-helper

**Comment by ghcsd** [comment]
支持，有种京豆的吗？

**Comment by zarkin404** [comment]
支持支持，顶顶顶！

**Comment by zarkin404** [comment]
你的项目链接已经放置到我的仓库 README 中了哈哈哈。

**Comment by liuxiaoyucc** [comment]
感谢感谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zarkin404"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月5日(星期五) 下午5:31
收件人:&nbsp;"zarkin404/sweater"<sweater@noreply.github.com&gt;;
抄送:&nbsp;"liuxy"<2199842341@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zarkin404/sweater] 受到大佬启发, 分享一个京东萌宠的 (#14)





 
你的项目链接已经放置到我的仓库 README 中了哈哈哈。
