### ISSUE TITLE
京东脚本今天执行发现所有浏览活动都不能成功

### ISSUE THREAD

**Issue by KaelInvoker** [zarkin404/sweater#15]
浏览接口全部报
JD:46 调用结果： {bizCode: -15, bizMsg: "活动太火爆了,稍后再试哦~", success: false}

**Comment by zarkin404** [comment]
你先在 APP 上手动点几个，然后再用脚本跑一下，我昨天也遇到了，不过今天就不会了，暂时不知道怎么回事。

**Comment by OKCup** [comment]
不行了，我也是这样

**Comment by TGhoul** [comment]
我也是这样，估计官方已经开始限制了。

**Comment by otwayz** [comment]
我也是这样

**Comment by zarkin404** [comment]
我现在跑了一遍，正常，可能部分账号有限制，你们今天手动做一下任务，明天再看看。前几天我也出现这个问题，就手动做了，第二天就正常了。

**Comment by KingAmo** [comment]
貌似做了限制了，我的也用不了了

**Comment by zarkin404** [comment]
Duplicate of #27
