### ISSUE TITLE
更新最新之后，出现“活动太火爆了,稍后再试哦”

### ISSUE THREAD

**Issue by PS0123456** [zarkin404/sweater#19]
调用结果： {bizCode: -15, bizMsg: "活动太火爆了,稍后再试哦~", success: false}
jd:32 @领取任务： {taskName: "去逛“华为”京东自营官方旗舰店", taskId: 5, taskType: 7, waitDuration: 8, itemId: "58463"}
jd:42 调用结果： {bizCode: -15, bizMsg: "活动太火爆了,稍后再试哦~", success: false}
jd:32 @执行任务： {taskName: "去逛“华为”京东自营官方旗舰店", taskId: 5, taskType: 7, waitDuration: 8, itemId: "58463"}
jd:42 调用结果： {bizCode: -15, bizMsg: "活动太火爆了,稍后再试哦~", success: false}
jd:32 @领取任务： {taskName: "去逛“华为”京东自营官方旗舰店", taskId: 5, taskType: 7, waitDuration: 8, itemId: "1000164464"}
jd:42 调用结果： {bizCode: -15, bizMsg: "活动太火爆了,稍后再试哦~", success: false}
jd:32 @执行任务： {taskName: "去逛“华为”京东自营官方旗舰店", taskId: 5, taskType: 7, waitDuration: 8, itemId: "1000164464"}
jd:42 调用结果： {bizCode: -15, bizMsg: "活动太火爆了,稍后再试哦~", success: false}
jd:32 @领取任务： {taskName: "去逛“华为”京东自营官方旗舰店", taskId: 5, taskType: 7, waitDuration: 8, itemId: "1000004259"}
jd:42 调用结果： {bizCode: -15, bizMsg: "活动太火爆了,稍后再试哦~", success: false}
jd:32 @执行任务： {taskName: "去逛“华为”京东自营官方旗舰店", taskId: 5, taskType: 7, waitDuration: 8, itemId: "1000004259"}
jd:42 调用结果： {bizCode: -15, bizMsg: "活动太火爆了,稍后再试哦~", success: false}
jd:32 @领取任务： {taskName: "去逛“华为”京东自营官方旗舰店", taskId: 5, taskType: 7, waitDuration: 8, itemId: "1000300901"}
jd:42 调用结果： {bizCode: -15, bizMsg: "活动太火爆了,稍后再试哦~", success: false}

是时间设置问题？调动太快？

**Comment by xoyi** [comment]
看了下api貌似有签名了

**Comment by zarkin404** [comment]
刚跑完脚本，正常的。同样的 issue：Duplicate of #15

**Comment by airsunwing** [comment]
部分项目黑号了
