### ISSUE TITLE
报错啦，未知错误

### ISSUE THREAD

**Issue by morooi** [zarkin404/sweater#2]
Uncaught (in promise) 未知错误
Promise.then (async)
(anonymous) @ JD:122
(anonymous) @ JD:200

Chrome 83.0.4103.61
已按照步骤设置好UA
用手机号登录和第三方授权都报一样的错

**Comment by zarkin404** [comment]
你截一下网络请求的图，我看看。client.action 结尾的那两个，然后切换到 preview 看一下报什么错。

**Comment by zarkin404** [comment]
> Uncaught (in promise) 未知错误
> Promise.then (async)
> (anonymous) @ JD:122
> (anonymous) @ JD:200
> 
> Chrome 83.0.4103.61
> 已按照步骤设置好UA
> 用手机号登录和第三方授权都报一样的错

你截一下网络请求的图，我看看。client.action 结尾的那两个，然后切换到 preview 看一下报什么错。

**Comment by morooi** [comment]
> > Uncaught (in promise) 未知错误
> > Promise.then (async)
> > (anonymous) @ JD:122
> > (anonymous) @ JD:200
> > Chrome 83.0.4103.61
> > 已按照步骤设置好UA
> > 用手机号登录和第三方授权都报一样的错
> 
> 你截一下网络请求的图，我看看。client.action 结尾的那两个，然后切换到 preview 看一下报什么错。

![](https://i.loli.net/2020/05/27/4Hb9eSKmnQPUaBT.jpg)
![](https://i.loli.net/2020/05/27/BQTCU8eA7z1jdi4.jpg)

**Comment by zarkin404** [comment]
> > > Uncaught (in promise) 未知错误
> > > Promise.then (async)
> > > (anonymous) @ JD:122
> > > (anonymous) @ JD:200
> > > Chrome 83.0.4103.61
> > > 已按照步骤设置好UA
> > > 用手机号登录和第三方授权都报一样的错
> > 
> > 
> > 你截一下网络请求的图，我看看。client.action 结尾的那两个，然后切换到 preview 看一下报什么错。
> 
> ![](https://camo.githubusercontent.com/9eb814466bdcd13a92bb2244e5611c7a6150c3cd/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30352f32372f3448623965534b6d6e5150556142542e6a7067)
> ![](https://camo.githubusercontent.com/c1d49cc55c95138d7ef9ec426b8a0ee68bca8510/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30352f32372f4251544355386541377a316a6469342e6a7067)

你看下你访问的是不是京东的移动页面，https://m.jd.com 这个。理应不会获取不了任务详情呀😂。

**Comment by morooi** [comment]
> > > > Uncaught (in promise) 未知错误
> > > > Promise.then (async)
> > > > (anonymous) @ JD:122
> > > > (anonymous) @ JD:200
> > > > Chrome 83.0.4103.61
> > > > 已按照步骤设置好UA
> > > > 用手机号登录和第三方授权都报一样的错
> > > 
> > > 
> > > 你截一下网络请求的图，我看看。client.action 结尾的那两个，然后切换到 preview 看一下报什么错。
> > 
> > 
> > ![](https://camo.githubusercontent.com/9eb814466bdcd13a92bb2244e5611c7a6150c3cd/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30352f32372f3448623965534b6d6e5150556142542e6a7067)
> > ![](https://camo.githubusercontent.com/c1d49cc55c95138d7ef9ec426b8a0ee68bca8510/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30352f32372f4251544355386541377a316a6469342e6a7067)
> 
> 你看下你访问的是不是京东的移动页面，https://m.jd.com 这个。理应不会获取不了任务详情呀😂。

访问的就是这个。有点奇怪😂

![](https://i.loli.net/2020/05/27/IcPq7WJdnZwDpY6.jpg)

**Comment by zarkin404** [comment]
奇怪了。。这个代码身边几个朋友都能运行，我先跟进一下。。

**Comment by PaulingLi** [comment]
> Uncaught (in promise) 未知错误
> Promise.then (async)
> (anonymous) @ JD:122
> (anonymous) @ JD:200
> 
> Chrome 83.0.4103.61
> 已按照步骤设置好UA
> 用手机号登录和第三方授权都报一样的错

一样的错误

**Comment by Jarry-xu** [comment]
老哥，你使用说明的图好像挂了，能修复一下吗

**Comment by zarkin404** [comment]
截止到目前只发现你们两例异常，可能和账号的有关吧。。我之前有个同事一直参加不了的京东的活动，他的号注册不到半个月。。所以估计是这个原因，你们看下你们的账号是不是有过什么异常操作。

**Comment by morooi** [comment]
那就不太清楚了，账号是plus会员，在手机端手动参加活动是没有问题的😔
