### ISSUE TITLE
淘宝报h5 request forbidden错误

### ISSUE THREAD

**Issue by yorkezhong** [zarkin404/sweater#26]
淘宝报h5 request forbidden错误，被封了么

**Comment by yefengfang** [comment]
+1

**Comment by lxk0301** [comment]
+2
![image](https://user-images.githubusercontent.com/21308593/84494086-7345f000-acdb-11ea-8517-91d29203b2a1.png)

**Comment by zarkin404** [comment]
淘宝已经失效，不打算更新了。
