### ISSUE TITLE
京东叠蛋糕应该有更新

### ISSUE THREAD

**Issue by NickSmm** [zarkin404/sweater#27]
有些任务调接口不一定能做了

**Comment by truecsj** [comment]
昨天只有一个号火爆,今天全部都火爆,只有一个不火爆了.为什么呢?

**Comment by jiangtj** [comment]
taskType为3时，开会员卡，需要授权，这个任务应该有更新

**Comment by zzan1** [comment]
今天好像不能用了

**Comment by westfly** [comment]
任务有大量的失败
![image](https://user-images.githubusercontent.com/1453169/84236001-7c8f5b00-ab29-11ea-84be-d6f97f70fd3a.png)

**Comment by truecsj** [comment]
作者来更新下咯

**Comment by Leecason** [comment]
现在只能完成部分任务。。

**Comment by Xiaohantx** [comment]
大部分任务都火爆了。。。

**Comment by FormatFish** [comment]
me too

**Comment by igangx** [comment]
今天已经完全不能用了

**Comment by bahamut322** [comment]
请问下不能用是传参的问题还是jd那边限制了还是其他什么？

**Comment by wenjunzhangp** [comment]
估计是被jd检测限制了，有没有大佬来修复一波~(手动狗头)

**Comment by CodeTips** [comment]
研究了下，secretp 值变了，可惜我不是前段，不知道怎么改。

**Comment by Xiaohantx** [comment]
> 研究了下，secretp值变了，可惜我不是前段，不知道怎么改。

抓包对比了下app上的内容，看了secretp还是一样的好像

**Comment by ilss** [comment]
浏览商品 需要在商品页面 停留8秒了  之前是这样吗？？

**Comment by h2oiswater** [comment]
抓包看调用完成任务的参数，safeStr字段脚本只传了secretp，刚才抓包看这个safeStr对象多了一些值，补上之后能跑了。

**Comment by CodeTips** [comment]
> 抓包看调用完成任务的参数，safeStr字段脚本只传了secretp，刚才抓包看这个safeStr对象多了一些值，补上之后能跑了。

改为之后分享出来吧，我也看到不一样了。可惜我不会改

**Comment by Xiaohantx** [comment]
> 抓包看初始化完成任务的参数，safeStr脚本只传了了secretp，刚才抓包看这个safeStr对象多了一些值，补上之后能跑了。

不知道是缺什么值，昨天抓的模拟请求时候 带secretp和istrue可以，但是加到脚本里还是不行。。

**Comment by CodeTips** [comment]
> > 抓包看初始化完成任务的参数，safeStr脚本只传了了secretp，刚才抓包看这个safeStr对象多了一些值，补上之后能跑了。
> 
> 不知道是缺什么值，昨天抓的模拟请求时候 带secretp和istrue可以，但是加到脚本里还是不行。。

{
    "is_trust":true,
    "sign":"",
    "fpb":"",
    "time":1591939493030,
    "encrypt":4,
    "nonstr":"9DbZl1FkNp",
    "info":"",
    "token":"",
    "appid":"50072",
    "sceneid":"ckCollectScore",
    "secretp":"",
    "buttonid":"11",
    "uid":""
}

多了一些参数，我把我一些敏感信息清空了

**Comment by Xiaohantx** [comment]
> > > 抓包看初始化完成任务的参数，safeStr脚本只传了了secretp，刚才抓包看这个safeStr对象多了一些值，补上之后能跑了。
> > 
> > 
> > 不知道是缺什么值，昨天抓的模拟请求时候 带secretp和istrue可以，但是加到脚本里还是不行。。
> 
> {
> "is_trust":true,
> "sign":"",
> "fpb":"",
> "time":1591939493030,
> "encrypt":4,
> "nonstr":"9DbZl1FkNp",
> "info":"",
> "token":"",
> "appid":"50072",
> "sceneid":"ckCollectScore",
> "secretp":"",
> "buttonid":"11",
> "uid":""
> }
> 
> 多了一些参数，我把我一些敏感信息清空了

我看见了，主要别的没看见哪个接口拿到的....我在模拟的时候只传is_trust和secretp也是成功

**Comment by bahamut322** [comment]
> > > 抓包看初始化完成任务的参数，safeStr脚本只传了了secretp，刚才抓包看这个safeStr对象多了一些值，补上之后能跑了。
> > 
> > 
> > 不知道是缺什么值，昨天抓的模拟请求时候 带secretp和istrue可以，但是加到脚本里还是不行。。
> 
> {
> "is_trust":true,
> "sign":"",
> "fpb":"",
> "time":1591939493030,
> "encrypt":4,
> "nonstr":"9DbZl1FkNp",
> "info":"",
> "token":"",
> "appid":"50072",
> "sceneid":"ckCollectScore",
> "secretp":"",
> "buttonid":"11",
> "uid":""
> }
> 
> 多了一些参数，我把我一些敏感信息清空了

请问下这些参数都要传吗，而且要如何获取到这些的value

**Comment by h2oiswater** [comment]
> > > > 抓包看初始化完成任务的参数，safeStr脚本只传了了secretp，刚才抓包看这个safeStr对象多了一些值，补上之后能跑了。
> > > 
> > > 
> > > 不知道是缺什么值，昨天抓的模拟请求时候 带secretp和istrue可以，但是加到脚本里还是不行。。
> > 
> > 
> > {
> > "is_trust":true,
> > "sign":"",
> > "fpb":"",
> > "time":1591939493030,
> > "encrypt":4,
> > "nonstr":"9DbZl1FkNp",
> > "info":"",
> > "token":"",
> > "appid":"50072",
> > "sceneid":"ckCollectScore",
> > "secretp":"",
> > "buttonid":"11",
> > "uid":""
> > }
> > 多了一些参数，我把我一些敏感信息清空了
> 
> 请问下这些参数都要传吗，而且要如何获取到这些的value

iOS可以用Thor，HttpCatcher

**Comment by bahamut322** [comment]
> > > > > 抓包看初始化完成任务的参数，safeStr脚本只传了了secretp，刚才抓包看这个safeStr对象多了一些值，补上之后能跑了。
> > > > 
> > > > 
> > > > 不知道是缺什么值，昨天抓的模拟请求时候 带secretp和istrue可以，但是加到脚本里还是不行。。
> > > 
> > > 
> > > {
> > > "is_trust":true,
> > > "sign":"",
> > > "fpb":"",
> > > "time":1591939493030,
> > > "encrypt":4,
> > > "nonstr":"9DbZl1FkNp",
> > > "info":"",
> > > "token":"",
> > > "appid":"50072",
> > > "sceneid":"ckCollectScore",
> > > "secretp":"",
> > > "buttonid":"11",
> > > "uid":""
> > > }
> > > 多了一些参数，我把我一些敏感信息清空了
> > 
> > 
> > 请问下这些参数都要传吗，而且要如何获取到这些的value
> 
> iOS可以用Thor，HttpCatcher

意思是全是定值来的？

**Comment by lvzhaoxing** [comment]
> > > > > > 抓包看初始化完成任务的参数，safeStr脚本只传了了secretp，刚才抓包看这个safeStr对象多了一些值，补上之后能跑了。
> > > > > 
> > > > > 
> > > > > 不知道是缺什么值，昨天抓的模拟请求时候 带secretp和istrue可以，但是加到脚本里还是不行。。
> > > > 
> > > > 
> > > > {
> > > > "is_trust":true,
> > > > "sign":"",
> > > > "fpb":"",
> > > > "time":1591939493030,
> > > > "encrypt":4,
> > > > "nonstr":"9DbZl1FkNp",
> > > > "info":"",
> > > > "token":"",
> > > > "appid":"50072",
> > > > "sceneid":"ckCollectScore",
> > > > "secretp":"",
> > > > "buttonid":"11",
> > > > "uid":""
> > > > }
> > > > 多了一些参数，我把我一些敏感信息清空了
> > > 
> > > 
> > > 请问下这些参数都要传吗，而且要如何获取到这些的value
> > 
> > 
> > iOS可以用Thor，HttpCatcher
> 
> 意思是全是定值来的？

肯定不会全部是定制，抓过几次包，sign，nonstr就是变动了

**Comment by bahamut322** [comment]
> > > > > > > 抓包看初始化完成任务的参数，safeStr脚本只传了了secretp，刚才抓包看这个safeStr对象多了一些值，补上之后能跑了。
> > > > > > 
> > > > > > 
> > > > > > 不知道是缺什么值，昨天抓的模拟请求时候 带secretp和istrue可以，但是加到脚本里还是不行。。
> > > > > 
> > > > > 
> > > > > {
> > > > > "is_trust":true,
> > > > > "sign":"",
> > > > > "fpb":"",
> > > > > "time":1591939493030,
> > > > > "encrypt":4,
> > > > > "nonstr":"9DbZl1FkNp",
> > > > > "info":"",
> > > > > "token":"",
> > > > > "appid":"50072",
> > > > > "sceneid":"ckCollectScore",
> > > > > "secretp":"",
> > > > > "buttonid":"11",
> > > > > "uid":""
> > > > > }
> > > > > 多了一些参数，我把我一些敏感信息清空了
> > > > 
> > > > 
> > > > 请问下这些参数都要传吗，而且要如何获取到这些的value
> > > 
> > > 
> > > iOS可以用Thor，HttpCatcher
> > 
> > 
> > 意思是全是定值来的？
> 
> 肯定不会全部是定制，抓过几次包，sign，nonstr就是变动了

跑成功了嘿嘿嘿

**Comment by Cooboob** [comment]
> > > > > > > > 抓包看初始化完成任务的参数，safeStr脚本只传了了secretp，刚才抓包看这个safeStr对象多了一些值，补上之后能跑了。
> > > > > > > 
> > > > > > > 
> > > > > > > 不知道是缺什么值，昨天抓的模拟请求时候 带secretp和istrue可以，但是加到脚本里还是不行。。
> > > > > > 
> > > > > > 
> > > > > > {
> > > > > > "is_trust":true,
> > > > > > "sign":"",
> > > > > > "fpb":"",
> > > > > > "time":1591939493030,
> > > > > > "encrypt":4,
> > > > > > "nonstr":"9DbZl1FkNp",
> > > > > > "info":"",
> > > > > > "token":"",
> > > > > > "appid":"50072",
> > > > > > "sceneid":"ckCollectScore",
> > > > > > "secretp":"",
> > > > > > "buttonid":"11",
> > > > > > "uid":""
> > > > > > }
> > > > > > 多了一些参数，我把我一些敏感信息清空了
> > > > > 
> > > > > 
> > > > > 请问下这些参数都要传吗，而且要如何获取到这些的value
> > > > 
> > > > 
> > > > iOS可以用Thor，HttpCatcher
> > > 
> > > 
> > > 意思是全是定值来的？
> > 
> > 
> > 肯定不会全部是定制，抓过几次包，sign，nonstr就是变动了
> 
> 跑成功了嘿嘿嘿

请问这2个的算法是什么?

**Comment by choucaicai** [comment]
> > > > > > > > 抓包看初始化完成任务的参数，safeStr脚本只传了了secretp，刚才抓包看这个safeStr对象多了一些值，补上之后能跑了。
> > > > > > > 
> > > > > > > 
> > > > > > > 不知道是缺什么值，昨天抓的模拟请求时候 带secretp和istrue可以，但是加到脚本里还是不行。。
> > > > > > 
> > > > > > 
> > > > > > {
> > > > > > "is_trust":true,
> > > > > > "sign":"",
> > > > > > "fpb":"",
> > > > > > "time":1591939493030,
> > > > > > "encrypt":4,
> > > > > > "nonstr":"9DbZl1FkNp",
> > > > > > "info":"",
> > > > > > "token":"",
> > > > > > "appid":"50072",
> > > > > > "sceneid":"ckCollectScore",
> > > > > > "secretp":"",
> > > > > > "buttonid":"11",
> > > > > > "uid":""
> > > > > > }
> > > > > > 多了一些参数，我把我一些敏感信息清空了
> > > > > 
> > > > > 
> > > > > 请问下这些参数都要传吗，而且要如何获取到这些的value
> > > > 
> > > > 
> > > > iOS可以用Thor，HttpCatcher
> > > 
> > > 
> > > 意思是全是定值来的？
> > 
> > 
> > 肯定不会全部是定制，抓过几次包，sign，nonstr就是变动了
> 
> 跑成功了嘿嘿嘿

怎么弄的

**Comment by h2oiswater** [comment]
> > > > > > > > > 抓包看初始化完成任务的参数，safeStr脚本只传了了secretp，刚才抓包看这个safeStr对象多了一些值，补上之后能跑了。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 不知道是缺什么值，昨天抓的模拟请求时候 带secretp和istrue可以，但是加到脚本里还是不行。。
> > > > > > > 
> > > > > > > 
> > > > > > > {
> > > > > > > "is_trust":true,
> > > > > > > "sign":"",
> > > > > > > "fpb":"",
> > > > > > > "time":1591939493030,
> > > > > > > "encrypt":4,
> > > > > > > "nonstr":"9DbZl1FkNp",
> > > > > > > "info":"",
> > > > > > > "token":"",
> > > > > > > "appid":"50072",
> > > > > > > "sceneid":"ckCollectScore",
> > > > > > > "secretp":"",
> > > > > > > "buttonid":"11",
> > > > > > > "uid":""
> > > > > > > }
> > > > > > > 多了一些参数，我把我一些敏感信息清空了
> > > > > > 
> > > > > > 
> > > > > > 请问下这些参数都要传吗，而且要如何获取到这些的value
> > > > > 
> > > > > 
> > > > > iOS可以用Thor，HttpCatcher
> > > > 
> > > > 
> > > > 意思是全是定值来的？
> > > 
> > > 
> > > 肯定不会全部是定制，抓过几次包，sign，nonstr就是变动了
> > 
> > 
> > 跑成功了嘿嘿嘿
> 
> 怎么弄的

需要一点点动手能力，在电脑或者手机上开启抓包软件，在APP上手动做一下任务，看看api.m.jd.com的接口参数
```
{
"is_trust":true,
"sign":"",
"fpb":"",
"time":1591939493030,
"encrypt":4,
"nonstr":"9DbZl1FkNp",
"info":"",
"token":"",
"appid":"50072",
"sceneid":"ckCollectScore",
"secretp":"",
"buttonid":"11",
"uid":""
}
```
把这些复制下来，放到脚本中再跑就行了

**Comment by igangx** [comment]
> {
> "is_trust":true,
> "sign":"",
> "fpb":"",
> "time":1591939493030,
> "encrypt":4,
> "nonstr":"9DbZl1FkNp",
> "info":"",
> "token":"",
> "appid":"50072",
> "sceneid":"ckCollectScore",
> "secretp":"",
> "buttonid":"11",
> "uid":""
> }

兄弟，能不能再说清楚点，是放在那个位置？什么样的格式？

**Comment by changer2222** [comment]
> > > > > > > > > > 抓包看初始化完成任务的参数，safeStr脚本只传了了secretp，刚才抓包看这个safeStr对象多了一些值，补上之后能跑了。
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 不知道是缺什么值，昨天抓的模拟请求时候 带secretp和istrue可以，但是加到脚本里还是不行。。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > {
> > > > > > > > "is_trust":true,
> > > > > > > > "sign":"",
> > > > > > > > "fpb":"",
> > > > > > > > "time":1591939493030,
> > > > > > > > "encrypt":4,
> > > > > > > > "nonstr":"9DbZl1FkNp",
> > > > > > > > "info":"",
> > > > > > > > "token":"",
> > > > > > > > "appid":"50072",
> > > > > > > > "sceneid":"ckCollectScore",
> > > > > > > > "secretp":"",
> > > > > > > > "buttonid":"11",
> > > > > > > > "uid":""
> > > > > > > > }
> > > > > > > > 多了一些参数，我把我一些敏感信息清空了
> > > > > > > 
> > > > > > > 
> > > > > > > 请问下这些参数都要传吗，而且要如何获取到这些的value
> > > > > > 
> > > > > > 
> > > > > > iOS可以用Thor，HttpCatcher
> > > > > 
> > > > > 
> > > > > 意思是全是定值来的？
> > > > 
> > > > 
> > > > 肯定不会全部是定制，抓过几次包，sign，nonstr就是变动了
> > > 
> > > 
> > > 跑成功了嘿嘿嘿
> > 
> > 
> > 怎么弄的
> 
> 需要一点点动手能力，在电脑或者手机上开启抓包软件，在APP上手动做一下任务，看看api.m.jd.com的接口参数
> 
> ```
> {
> "is_trust":true,
> "sign":"",
> "fpb":"",
> "time":1591939493030,
> "encrypt":4,
> "nonstr":"9DbZl1FkNp",
> "info":"",
> "token":"",
> "appid":"50072",
> "sceneid":"ckCollectScore",
> "secretp":"",
> "buttonid":"11",
> "uid":""
> }
> ```
> 
> 把这些复制下来，放到脚本中再跑就行了

能否把脚本share一下看看呢？
主要是这些会动的变量值怎么get的？

**Comment by cavielle** [comment]
> > > > > > > > > > > 抓包看初始化完成任务的参数，safeStr脚本只传了了secretp，刚才抓包看这个safeStr对象多了一些值，补上之后能跑了。
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 不知道是缺什么值，昨天抓的模拟请求时候 带secretp和istrue可以，但是加到脚本里还是不行。。
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > {
> > > > > > > > > "is_trust":true,
> > > > > > > > > "sign":"",
> > > > > > > > > "fpb":"",
> > > > > > > > > "time":1591939493030,
> > > > > > > > > "encrypt":4,
> > > > > > > > > "nonstr":"9DbZl1FkNp",
> > > > > > > > > "info":"",
> > > > > > > > > "token":"",
> > > > > > > > > "appid":"50072",
> > > > > > > > > "sceneid":"ckCollectScore",
> > > > > > > > > "secretp":"",
> > > > > > > > > "buttonid":"11",
> > > > > > > > > "uid":""
> > > > > > > > > }
> > > > > > > > > 多了一些参数，我把我一些敏感信息清空了
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 请问下这些参数都要传吗，而且要如何获取到这些的value
> > > > > > > 
> > > > > > > 
> > > > > > > iOS可以用Thor，HttpCatcher
> > > > > > 
> > > > > > 
> > > > > > 意思是全是定值来的？
> > > > > 
> > > > > 
> > > > > 肯定不会全部是定制，抓过几次包，sign，nonstr就是变动了
> > > > 
> > > > 
> > > > 跑成功了嘿嘿嘿
> > > 
> > > 
> > > 怎么弄的
> > 
> > 
> > 需要一点点动手能力，在电脑或者手机上开启抓包软件，在APP上手动做一下任务，看看api.m.jd.com的接口参数
> > ```
> > {
> > "is_trust":true,
> > "sign":"",
> > "fpb":"",
> > "time":1591939493030,
> > "encrypt":4,
> > "nonstr":"9DbZl1FkNp",
> > "info":"",
> > "token":"",
> > "appid":"50072",
> > "sceneid":"ckCollectScore",
> > "secretp":"",
> > "buttonid":"11",
> > "uid":""
> > }
> > ```
> > 
> > 
> > 把这些复制下来，放到脚本中再跑就行了
> 
> 能否把脚本share一下看看呢？
> 主要是这些会动的变量值怎么get的？

![image](https://user-images.githubusercontent.com/43660383/84592564-37e12800-ae79-11ea-806a-4fa5a8d00c7a.png)
就和上面那位老哥说的抓包之后看看api.m.jd.com的接口参数，然后在这里替换掉就行了，定值

**Comment by changer2222** [comment]
> 就和上面那位老哥说的抓包之后看看api.m.jd.com的接口参数，然后在这里替换掉就行了，定值

奇怪，这些除了secretp是变动外，其他的都是固定值吗？我抓包后有几个值是来回变的。
你每天执行的时候去替换当天的吗？

**Comment by ilss** [comment]
> > > > > > > > > > > > 抓包看初始化完成任务的参数，safeStr脚本只传了了secretp，刚才抓包看这个safeStr对象多了一些值，补上之后能跑了。
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 不知道是缺什么值，昨天抓的模拟请求时候 带secretp和istrue可以，但是加到脚本里还是不行。。
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > {
> > > > > > > > > > "is_trust":true,
> > > > > > > > > > "sign":"",
> > > > > > > > > > "fpb":"",
> > > > > > > > > > "time":1591939493030,
> > > > > > > > > > "encrypt":4,
> > > > > > > > > > "nonstr":"9DbZl1FkNp",
> > > > > > > > > > "info":"",
> > > > > > > > > > "token":"",
> > > > > > > > > > "appid":"50072",
> > > > > > > > > > "sceneid":"ckCollectScore",
> > > > > > > > > > "secretp":"",
> > > > > > > > > > "buttonid":"11",
> > > > > > > > > > "uid":""
> > > > > > > > > > }
> > > > > > > > > > 多了一些参数，我把我一些敏感信息清空了
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 请问下这些参数都要传吗，而且要如何获取到这些的value
> > > > > > > > 
> > > > > > > > 
> > > > > > > > iOS可以用Thor，HttpCatcher
> > > > > > > 
> > > > > > > 
> > > > > > > 意思是全是定值来的？
> > > > > > 
> > > > > > 
> > > > > > 肯定不会全部是定制，抓过几次包，sign，nonstr就是变动了
> > > > > 
> > > > > 
> > > > > 跑成功了嘿嘿嘿
> > > > 
> > > > 
> > > > 怎么弄的
> > > 
> > > 
> > > 需要一点点动手能力，在电脑或者手机上开启抓包软件，在APP上手动做一下任务，看看api.m.jd.com的接口参数
> > > ```
> > > {
> > > "is_trust":true,
> > > "sign":"",
> > > "fpb":"",
> > > "time":1591939493030,
> > > "encrypt":4,
> > > "nonstr":"9DbZl1FkNp",
> > > "info":"",
> > > "token":"",
> > > "appid":"50072",
> > > "sceneid":"ckCollectScore",
> > > "secretp":"",
> > > "buttonid":"11",
> > > "uid":""
> > > }
> > > ```
> > > 
> > > 
> > > 把这些复制下来，放到脚本中再跑就行了
> > 
> > 
> > 能否把脚本share一下看看呢？
> > 主要是这些会动的变量值怎么get的？
> 
> ![image](https://user-images.githubusercontent.com/43660383/84592564-37e12800-ae79-11ea-806a-4fa5a8d00c7a.png)
> 就和上面那位老哥说的抓包之后看看api.m.jd.com的接口参数，然后在这里替换掉就行了，定值

替换这里 不序列化    已经又可以跑了。

**Comment by igangx** [comment]
> > 就和上面那位老哥说的抓包之后看看api.m.jd.com的接口参数，然后在这里替换掉就行了，定值
> 
> 奇怪，这些除了secretp是变动外，其他的都是固定值吗？我抓包后有几个值是来回变的。
> 你每天执行的时候去替换当天的吗？

我用其中一次抓到的值替换以后，连续两天都可以跑了，不用每天替换。

**Comment by FFMonster** [comment]
https://api.m.jd.com/client.action?functionId=cakebaker_ckCollectScore
我是在这个接口获取到的safeStr。使用的app是HttpCanary
![2](https://user-images.githubusercontent.com/31976895/84729968-8b618c00-afc7-11ea-9a38-e4a85ae8f6d7.png)

将safeStr 内JSON 去除转义后放入 main.js 内，实测运行成功

![3](https://user-images.githubusercontent.com/31976895/84730327-75a09680-afc8-11ea-931e-c12b81d04d79.png)

**Comment by LuckyBoat** [comment]
请问为什么我用的哨口(whistle)的请求是这种加密的？
![1](https://user-images.githubusercontent.com/58982312/84742516-1d2ac280-afe3-11ea-82f2-7d40d1bdf0cd.jpg)

**Comment by h2oiswater** [comment]
> 请问为什么我用的哨口(whistle)的请求是这种加密的？
> ![1](https://user-images.githubusercontent.com/58982312/84742516-1d2ac280-afe3-11ea-82f2-7d40d1bdf0cd.jpg)

这个只是UrlEncode了，搜在线UrlDecode，哪个接口看楼上 @LuckyBoat 的

**Comment by LuckyBoat** [comment]
> > 请问为什么我用的哨口（whistle）的请求是这种加密的？
> > ![1个](https://user-images.githubusercontent.com/58982312/84742516-1d2ac280-afe3-11ea-82f2-7d40d1bdf0cd.jpg)
> 
> 这个只是UrlEncode了，搜在线UrlDecode，那个接口看楼上@LuckyBoat的

请问接口怎么用啊？ @h2oiswater

**Comment by LuckyBoat** [comment]
这个什么也没有啊？
![1](https://user-images.githubusercontent.com/58982312/84745018-8e1fa980-afe6-11ea-97fd-49caec7dc084.jpg)
@h2oiswater

**Comment by LuckyBoat** [comment]
不会搞啊，有木有大佬指点一下

**Comment by LuckyBoat** [comment]
搞了一下午，终于是弄好了啊！
![1](https://user-images.githubusercontent.com/58982312/84777904-c5a54a80-b014-11ea-8512-0b27e4df3a12.jpg)

**Comment by hzyhbk** [comment]
补充下，抓的是 `api.m.jd.com/client.action` 这个接口的参数,抓到之后整个复制进去替换掉就好了
![image](https://user-images.githubusercontent.com/42671099/84851748-b44c5480-b08d-11ea-89ff-c2632f083002.png)

**Comment by imReker** [comment]
好像又被封了? safeStr去掉转义放进脚本还是活动火爆。 UA用的就是jdapp

Edit：
手动看了一下，脚本里的过滤条件写错了，`/助力|站队`这里错别字，`战`

**Comment by ilss** [comment]
6块钱。。。。 大家分了多少？？？

**Comment by igangx** [comment]
> 6块钱。。。。 大家分了多少？？？

174.7 👍

**Comment by zarkin404** [comment]
> 6块钱。。。。 大家分了多少？？？

23.24

**Comment by LuckyBoat** [comment]
11..........

**Comment by LuckyBoat** [comment]
> 6块钱。。。。。大家都了多少？？？

11...........

**Comment by zarkin404** [comment]
今晚的叠蛋糕瓜分红包 36.58，加上战队红包，助力红包一共 60 多块，全程超佛系。。。

**Comment by lero007** [comment]
> 今晚的叠蛋糕瓜分红包 36.58，加上战队红包，助力红包一共 60 多块，全程超佛系。。。

我蛋糕也是36.58。。。PK那个最后搞了3天，73块多、
