### ISSUE TITLE
运行不成功

### ISSUE THREAD

**Issue by Young-Joe** [zarkin404/sweater#3]
我UA创建了Custom-JD,运行脚本.
`m.jd.com/:1 Uncaught (in promise) 任务详情获取失败，请确保已设置正确的浏览器 User-Agent。
Promise.then (async)
(anonymous) @ JD:131
(anonymous) @ JD:196`

**Comment by zarkin404** [comment]
> 我UA创建了Custom-JD,运行脚本.
> `m.jd.com/:1 Uncaught (in promise) 任务详情获取失败，请确保已设置正确的浏览器 User-Agent。 Promise.then (async) (anonymous) @ JD:131 (anonymous) @ JD:196`

那就是没成功设置啦，你看一下上面我 log 出来的 UA 信息，应该没有 jdapp 的字样。

**Comment by Young-Joe** [comment]
UA的jdapp不是你自己自定义添加的么?我是安装你图自定义添加的

**Comment by zarkin404** [comment]
> UA的jdapp不是你自己自定义添加的么?我是安装你图自定义添加的

我刚更新了 README，你看一下，可以不用插件了
