### ISSUE TITLE
京东任务没有清完

### ISSUE THREAD

**Issue by jiuyuan-yuan** [zarkin404/sweater#32]
重复执行了几次，京东的任务没有执行完，可能是部分店铺更新？地址变更导致

**Comment by JKevin-5** [comment]
好像是将开通店铺会员的任务加到了任务列表里了，和自动浏览的逻辑好像不太相同，可以屏蔽

**Comment by sea72** [comment]
> 好像是将开通店铺会员的任务加到了任务列表里了，和自动浏览的逻辑好像不太相同，可以屏蔽

嗯，似乎是这样，任务序列只有固定长度，前25个都是开通店铺会员。有什么处理办法么

**Comment by zarkin404** [comment]
> > 好像是将开通店铺会员的任务加到了任务列表里了，和自动浏览的逻辑好像不太相同，可以屏蔽
> 
> 嗯，似乎是这样，任务序列只有固定长度，前25个都是开通店铺会员。有什么处理办法么

暂时没办法处理，还没找到任务所在的接口。
