### ISSUE TITLE
猫咪

### ISSUE THREAD

**Issue by ericellis7** [zarkin404/sweater#37]
可以改猫咪了 是不哈哈？

**Comment by Formerly** [comment]
楼下表示认同楼上

**Comment by Lbosen** [comment]
老板，又双十一了，今年还多了拼多多

**Comment by zarkin404** [comment]
就做了个京东，其他没头发做啦。。。[2020 京东双 11 全民营业活动](https://github.com/zarkin404/sweater/tree/master/jingdong/2020_cake_baker)
