### ISSUE TITLE
全民营业左上角营业版图自动领能作不？

### ISSUE THREAD

**Issue by changer2222** [zarkin404/sweater#41]
全民营业左上角营业版图自动领能作不？

**Comment by zarkin404** [comment]
支持了。emmmm.... 本来不想写的，免得薅到人家一滴不剩，但后面自己点的时候嗨烦，所以改改就支持了。（东哥，对不住了。。。）

**Comment by changer2222** [comment]
确实比较烦，能自动的还是不错的
