### ISSUE TITLE
又出现任务火爆了

### ISSUE THREAD

**Issue by changer2222** [zarkin404/sweater#44]
618的时候的也出现的，后来怎么修改的。
昨天晚上开始听说好多脚本报任务火爆的提示。因昨天早上执行了，所以没有在意
今天刚运行也不行了

**Comment by Formerly** [comment]
+1

**Comment by Dewforest** [comment]
+1

**Comment by terry386** [comment]
+1

**Comment by Celeter** [comment]
+1

**Comment by ccnana** [comment]
抓接口，获取得分的接口增加了token和签名等参数

**Comment by CoderJChen** [comment]
抓包出来不太能用

**Comment by zarkin404** [comment]
部分出现任务火爆的用户请自行想办法手动做任务吧，多半是进入了京东的风控黑名单，所以每个关键请求就会校验签名。。暂时没想到解决办法，因为签名的流程是在 APP 原生层面上做的，没空研究。
