### ISSUE TITLE
老哥，再搞个天猫的

### ISSUE THREAD

**Issue by xoyi** [zarkin404/sweater#7]

**Comment by wl386123298** [comment]
+1

**Comment by xiaodesetingyongzhanghao** [comment]
+2

**Comment by Rico358097990** [comment]
+3

**Comment by wuxi889** [comment]
+4

**Comment by LJYes** [comment]
+5

**Comment by xiaodou-max** [comment]
+6

**Comment by Lbosen** [comment]
+7

**Comment by charminghiker** [comment]
+8

**Comment by wangyupo** [comment]
+9

**Comment by LoveFForever** [comment]
+10

**Comment by jueran** [comment]
+11

**Comment by zhuanghaotang** [comment]
+12

**Comment by xjh1017** [comment]
+13

**Comment by shrekuu** [comment]
+14

**Comment by IkeFwd** [comment]
+15

**Comment by king-zxw** [comment]
+16

**Comment by strivecheng** [comment]
+17

**Comment by yefengfang** [comment]
+18

**Comment by wsfy15** [comment]
+19

**Comment by wishcn** [comment]
+20

**Comment by gang0122** [comment]
+21

**Comment by h-ecstasy** [comment]
+22

**Comment by zhangenming** [comment]
+22++

**Comment by Woooosz** [comment]
+23

**Comment by huozhicheng** [comment]
+1

**Comment by 18059103437** [comment]
+24

**Comment by iok-pixel** [comment]
+25

**Comment by seame1on** [comment]
+26

**Comment by Answergeng** [comment]
+10000

**Comment by sqy941013** [comment]
+27

**Comment by gutianyi** [comment]
+28

**Comment by abcdGJJ** [comment]
+29

**Comment by lero007** [comment]
+10086

**Comment by KaelInvoker** [comment]
+30

**Comment by Erlla** [comment]
+31

**Comment by wintercoder** [comment]
+32 mark

**Comment by Jialufeng** [comment]
+33

**Comment by zl939144892** [comment]
+34

**Comment by otwayz** [comment]
+35

**Comment by ericellis7** [comment]
+36

**Comment by zarkin404** [comment]
时间有限，只做了一个简单版本，请各位见谅。[淘宝 618 理想列车](https://github.com/zarkin404/sweater/tree/master/taobao/2020_ideal_train)

**Comment by xoyi** [comment]
> 时间有限，只做了一个简单版本，请各位见谅。[淘宝 618 理想列车](https://github.com/zarkin404/sweater/tree/master/taobao/2020_ideal_train)

赞，40+留言炸出了新品，哈哈

**Comment by zarkin404** [comment]
> > 时间有限，只做了一个简单版本，请各位见谅。[淘宝 618 理想列车](https://github.com/zarkin404/sweater/tree/master/taobao/2020_ideal_train)
> 
> 赞，40+留言炸出了新品，哈哈

天天被 github notification 震，不想做又觉得枉费各位的期待，做了又怕没时间做不好，现在只能是先一个残疾的版本顶着了。😂😂😂

**Comment by xoyi** [comment]
> > > 时间有限，只做了一个简单版本，请各位见谅。[淘宝 618 理想列车](https://github.com/zarkin404/sweater/tree/master/taobao/2020_ideal_train)
> > 
> > 
> > 赞，40+留言炸出了新品，哈哈
> 
> 天天被 github notification 震，不想做又觉得枉费各位的期待，做了又怕没时间做不好，现在只能是先一个残疾的版本顶着了。

我也天天被震哈哈

**Comment by huozhicheng** [comment]
{errorCode: "system_close", errorMsg: "h5 request forbidden", now: "2020-06-05 16:58:15"}

无权限
