### ISSUE TITLE
脚本执行报错

### ISSUE THREAD

**Issue by ppp1234** [zarkin404/sweater#8]
最新版chrome，已设置 jdapp，执行脚本时console报错如下：

💡 正在执行第 1 轮任务，还有 2 轮未执行。
jd:19 Refused to connect to 'https://api.m.jd.com/client.action' because it violates the following Content Security Policy directive: "connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events wss://live.github.com".

request @ jd:19
(anonymous) @ jd:126
main @ jd:197
excuteMain @ jd:208
(anonymous) @ jd:220
jd:19 Refused to connect to 'https://api.m.jd.com/client.action' because it violates the document's Content Security Policy.
request @ jd:19
(anonymous) @ jd:126
main @ jd:197
excuteMain @ jd:208
(anonymous) @ jd:220
jd:1 undefined
jd:19 Uncaught (in promise) TypeError: Failed to fetch
    at request (jd:19)
    at jd:126
    at main (jd:197)
    at new Promise (<anonymous>)
    at excuteMain (jd:208)
    at jd:220
request @ jd:19
(anonymous) @ jd:126
main @ jd:197
excuteMain @ jd:208
(anonymous) @ jd:220
Promise.then (async)
(anonymous) @ jd:137
main @ jd:197
excuteMain @ jd:208
(anonymous) @ jd:220
jd:19 Refused to connect to 'https://api.m.jd.com/client.action' because it violates the following Content Security Policy directive: "connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events wss://live.github.com".

request @ jd:19
(anonymous) @ jd:130
setTimeout (async)
(anonymous) @ jd:129
(anonymous) @ jd:128
main @ jd:197
excuteMain @ jd:208
(anonymous) @ jd:220
jd:19 Refused to connect to 'https://api.m.jd.com/client.action' because it violates the document's Content Security Policy.
request @ jd:19
(anonymous) @ jd:130
setTimeout (async)
(anonymous) @ jd:129
(anonymous) @ jd:128
main @ jd:197
excuteMain @ jd:208
(anonymous) @ jd:220
jd:19 Uncaught (in promise) TypeError: Failed to fetch
    at request (jd:19)
    at jd:130
request @ jd:19
(anonymous) @ jd:130
Promise.then (async)
(anonymous) @ jd:130
setTimeout (async)
(anonymous) @ jd:129
(anonymous) @ jd:128
main @ jd:197
excuteMain @ jd:208
(anonymous) @ jd:220
analytics.min.js:6 POST https://www.google-analytics.com/collect net::ERR_BLOCKED_BY_CLIENT
N @ frameworks-2151adfd.js:1
V @ frameworks-2151adfd.js:1
(anonymous) @ tslib.es6.js:53
I.D @ frameworks-2151adfd.js:1
Sn.send @ frameworks-2151adfd.js:1
Xe.e.<computed> @ frameworks-2151adfd.js:1
zn.v @ frameworks-2151adfd.js:1
zn.D @ frameworks-2151adfd.js:1
Jn @ frameworks-2151adfd.js:1
B @ frameworks-2151adfd.js:1
(anonymous) @ tslib.es6.js:53
st @ render.js:44
google-analytics-octolytics.ts:14 POST https://collector.githubapp.com/collect net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ tslib.es6.js:53
I.D @ frameworks-2151adfd.js:1
Sn.send @ frameworks-2151adfd.js:1
Xe.e.<computed> @ frameworks-2151adfd.js:1
zn.v @ frameworks-2151adfd.js:1
zn.D @ frameworks-2151adfd.js:1
Jn @ frameworks-2151adfd.js:1
B @ frameworks-2151adfd.js:1
(anonymous) @ tslib.es6.js:53
st @ render.js:44
analytics.min.js:6 POST https://www.google-analytics.com/collect net::ERR_BLOCKED_BY_CLIENT
N @ frameworks-2151adfd.js:1
V @ frameworks-2151adfd.js:1
(anonymous) @ tslib.es6.js:53
I.D @ frameworks-2151adfd.js:1
Sn.send @ frameworks-2151adfd.js:1
Xe.e.<computed> @ frameworks-2151adfd.js:1
zn.v @ frameworks-2151adfd.js:1
zn.D @ frameworks-2151adfd.js:1
Jn @ frameworks-2151adfd.js:1
B @ frameworks-2151adfd.js:1
(anonymous) @ tslib.es6.js:53
st @ render.js:44
google-analytics-octolytics.ts:14 POST https://collector.githubapp.com/collect net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ tslib.es6.js:53
I.D @ frameworks-2151adfd.js:1
Sn.send @ frameworks-2151adfd.js:1
Xe.e.<computed> @ frameworks-2151adfd.js:1
zn.v @ frameworks-2151adfd.js:1
zn.D @ frameworks-2151adfd.js:1
Jn @ frameworks-2151adfd.js:1
B @ frameworks-2151adfd.js:1
(anonymous) @ tslib.es6.js:53
st @ render.js:44
analytics.min.js:6 POST https://www.google-analytics.com/collect net::ERR_BLOCKED_BY_CLIENT
N @ frameworks-2151adfd.js:1
V @ frameworks-2151adfd.js:1
(anonymous) @ tslib.es6.js:53
I.D @ frameworks-2151adfd.js:1
Sn.send @ frameworks-2151adfd.js:1
Xe.e.<computed> @ frameworks-2151adfd.js:1
zn.v @ frameworks-2151adfd.js:1
zn.D @ frameworks-2151adfd.js:1
Jn @ frameworks-2151adfd.js:1
B @ frameworks-2151adfd.js:1
(anonymous) @ tslib.es6.js:53
st @ render.js:44
google-analytics-octolytics.ts:14 POST https://collector.githubapp.com/collect net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ tslib.es6.js:53
I.D @ frameworks-2151adfd.js:1
Sn.send @ frameworks-2151adfd.js:1
Xe.e.<computed> @ frameworks-2151adfd.js:1
zn.v @ frameworks-2151adfd.js:1
zn.D @ frameworks-2151adfd.js:1
Jn @ frameworks-2151adfd.js:1
B @ frameworks-2151adfd.js:1
(anonymous) @ tslib.es6.js:53
st @ render.js:44
analytics.min.js:6 POST https://www.google-analytics.com/collect net::ERR_BLOCKED_BY_CLIENT
N @ frameworks-2151adfd.js:1
V @ frameworks-2151adfd.js:1
(anonymous) @ tslib.es6.js:53
I.D @ frameworks-2151adfd.js:1
Sn.send @ frameworks-2151adfd.js:1
Xe.e.<computed> @ frameworks-2151adfd.js:1
zn.v @ frameworks-2151adfd.js:1
zn.D @ frameworks-2151adfd.js:1
Jn @ frameworks-2151adfd.js:1
B @ frameworks-2151adfd.js:1
(anonymous) @ tslib.es6.js:53
st @ render.js:44
google-analytics-octolytics.ts:14 POST https://collector.githubapp.com/collect net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ tslib.es6.js:53
I.D @ frameworks-2151adfd.js:1
Sn.send @ frameworks-2151adfd.js:1
Xe.e.<computed> @ frameworks-2151adfd.js:1
zn.v @ frameworks-2151adfd.js:1
zn.D @ frameworks-2151adfd.js:1
Jn @ frameworks-2151adfd.js:1
B @ frameworks-2151adfd.js:1
(anonymous) @ tslib.es6.js:53
st @ render.js:44
analytics.min.js:6 POST https://www.google-analytics.com/collect net::ERR_BLOCKED_BY_CLIENT
N @ frameworks-2151adfd.js:1
V @ frameworks-2151adfd.js:1
(anonymous) @ tslib.es6.js:53
I.D @ frameworks-2151adfd.js:1
Sn.send @ frameworks-2151adfd.js:1
Xe.e.<computed> @ frameworks-2151adfd.js:1
zn.v @ frameworks-2151adfd.js:1
zn.D @ frameworks-2151adfd.js:1
Jn @ frameworks-2151adfd.js:1
B @ frameworks-2151adfd.js:1
(anonymous) @ tslib.es6.js:53
st @ render.js:44
google-analytics-octolytics.ts:14 POST https://collector.githubapp.com/collect net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ tslib.es6.js:53
I.D @ frameworks-2151adfd.js:1
Sn.send @ frameworks-2151adfd.js:1
Xe.e.<computed> @ frameworks-2151adfd.js:1
zn.v @ frameworks-2151adfd.js:1
zn.D @ frameworks-2151adfd.js:1
Jn @ frameworks-2151adfd.js:1
B @ frameworks-2151adfd.js:1
(anonymous) @ tslib.es6.js:53
st @ render.js:44

**Comment by zarkin404** [comment]
看一下是不是浏览器的插件导致问题。

**Comment by jbts6** [comment]
ERR_BLOCKED_BY_CLIENT   这个大可能是adblock引起的

**Comment by liuxiaoyucc** [comment]
大佬, 遇到同样的问题,这该如何解决?
![image](https://user-images.githubusercontent.com/33248133/83498821-fd79a180-a4ee-11ea-9c31-0d9acb4cd374.png)

**Comment by WhiteLeaf36** [comment]
> 大佬，遇到同样的问题，这该如何解决？
> ![图片](https://user-images.githubusercontent.com/33248133/83498821-fd79a180-a4ee-11ea-9c31-0d9acb4cd374.png)
你重新登陆试一下看看

**Comment by WhiteLeaf36** [comment]
你重新登陆试一下看看

**Comment by liuxiaoyucc** [comment]
> 你重新登陆试一下看看
重新登录后也没用, 换浏览器也没用, 知道是什么原因吗? 或者有啥解决办法?

**Comment by Shaun-Yao** [comment]
我关掉“京价保”插件就正常了

**Comment by liuxiaoyucc** [comment]
可以了，是我操作出了问题，感谢

**Comment by zarkin404** [comment]
跑脚本出问题时请尝试关闭浏览器扩展，如一些广告屏蔽扩展。
